// USERS
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS';
export const SET_CURRENT_USER_FAILURE = 'SET_CURRENT_USER_FAILURE';
export const POST_USER_DATA = 'POST_USER_DATA';
export const POST_USER_DATA_SUCCESS = 'POST_USER_DATA_SUCCESS';
export const POST_USER_DATA_FAILURE = 'POST_USER_DATA_FAILURE';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';
export const LOG_OUT_USER = "LOG_OUT_USER";

// UTILS
export const LOAD_FONTS = 'LOAD_FONTS';
export const LOAD_FONTS_SUCCESS = 'LOAD_FONTS_SUCCESS';
export const LOAD_FONTS_FAILURE = 'LOAD_FONTS_FAILURE';
