// USERS
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS';
export const SET_CURRENT_USER_FAILURE = 'SET_CURRENT_USER_FAILURE';
export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE';
export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_IN_USER_SUCCESS = 'LOG_IN_USER_SUCCESS';
export const LOG_IN_USER_FAILURE = 'LOG_IN_USER_FAILURE';
export const LOG_OUT_USER = "LOG_OUT_USER";

// UTILS
export const LOAD_FONTS = 'LOAD_FONTS';
export const LOAD_FONTS_SUCCESS = 'LOAD_FONTS_SUCCESS';
export const LOAD_FONTS_FAILURE = 'LOAD_FONTS_FAILURE';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// IDEAS
export const CREATE_IDEA = "CREATE_IDEA";
export const CREATE_IDEA_SUCCESS = "CREATE_IDEA_SUCCESS";
export const CREATE_IDEA_FAILURE = "CREATE_IDEA_FAILURE";
export const EDIT_IDEA = "EDIT_IDEA";
export const REMOVE_IDEA_ON_FOCUS = "REMOVE_IDEA_ON_FOCUS";
export const UPDATE_IDEA = "UPDATE_IDEA";
export const UPDATE_IDEA_SUCCESS = "UPDATE_IDEA_SUCCESS";
export const UPDATE_IDEA_FAILURE = "UPDATE_IDEA_FAILURE";
export const GET_ALL_IDEAS = "GET_ALL_IDEAS";
export const GET_ALL_IDEAS_SUCCESS = "GET_ALL_IDEAS_SUCCESS";
export const GET_ALL_IDEAS_FAILURE = "GET_ALL_IDEAS_FAILURE";
export const GET_IDEA = "GET_IDEA";
export const DELETE_IDEA = "DELETE_IDEA";
export const DELETE_IDEA_SUCCESS = "DELETE_IDEA_SUCCESS";
export const DELETE_IDEA_FAILURE = "DELETE_IDEA_FAILURE";
export const SORT_IDEAS = "SORT_IDEAS";
